# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "consistent_company"
  s.version = "0.0.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Doug Cleven"]
  s.date = "2015-03-24"
  s.description = "Ruby C Extension to normalize a company name. Useful when company names come from various sources."
  s.email = "dcleven@marketron.com"
  s.extensions = ["ext/consistent_company/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "ext/consistent_company/consistent_company.c",
    "lib/consistent_company.rb",
    "lib/consistent_company/version.rb"
  ]
  s.homepage = "http://github.com/dcleven/consistent_company"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Normalize a company name for consistent matching"

  s.add_dependency(%q<bundler>)
  s.add_dependency(%q<jeweler>)
  s.add_dependency(%q<rake-compiler>)
end

